package me.jannik.rplace.scoreboard;

import org.bukkit.ChatColor;
import org.bukkit.scoreboard.Team;

import javax.annotation.Nullable;

/**
 * This class has been generated by Jannik on 26.12.2021 13:34
 * You are not allowed to edit this resource or other components of it
 * © 2021 Jannik
 */

public class BasicScoreboardText implements ScoreboardText {

    private String text, extendedText, identifier;
    private boolean extended;

    public BasicScoreboardText(String text) {
        setText(text);
        this.identifier = null;
    }

    public BasicScoreboardText(String text, String identifier) {
        setText(text);
        this.identifier = identifier;
    }

    @Override
    public void apply(Team team) {
        team.setPrefix(this.text);
        team.setSuffix(ChatColor.getLastColors(this.text) + this.extendedText);
    }

    public void setText(String text) {
        if(text.length() > 16) {
            this.extended = true;
            this.extendedText = text.substring(16);
            this.text = text.substring(0, 16);
        } else {
            this.extended = false;
            this.text = text;
            this.extendedText = "";
        }
    }

    @Nullable
    @Override
    public String getIdentifier() {
        return identifier;
    }
}
